name: Checks
on: pull_request
jobs:
  checkout_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v3
        with:
          name: my-checkout-${{ github.run_id }}
          path: ${{ github.workspace }}/**/*
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

  run_lint:
    needs: checkout_install
    uses: ./.github/workflows/_lint.yml
